### ISSUE TITLE
Wrong timecode of pes+mui

### ISSUE THREAD

**Issue by Alllen** [cubicibo/ScenariStream#3]
Hi cubicibo,
I made sup and pes+mui files with SUPer, and I noticed in the Scenarist that the timecode of the pes file was wrong (starting with Epoch#899 DisplaySet#176), while the time of the simultaneous output of the sup file was perfectly correct. I then tried to convert that pes file to a sup file using ScenariStream and observed that the time was also correct and consistent with the sup file generated directly by SUPer.

-------------Epoch#899 DisplaySet#175-------------
![Image](https://github.com/user-attachments/assets/4010ac4c-71a1-4ea4-8bdd-f88eb5b76488)
-------------Epoch#899 DisplaySet#176-------------
![Image](https://github.com/user-attachments/assets/8062c24b-9097-460d-ae78-6b0045cafcee)
-------------Epoch#899 DisplaySet#177-------------
![Image](https://github.com/user-attachments/assets/692dbf1d-1b13-47c1-b975-a763ba9082cb)

**Comment by cubicibo** [comment]
Ouch! This issue is very difficult to debug without a .SUP file. Please send a .SUP and the value of the very fist InTC ( 0000000.png InTC )

If you do not want to share it publicly, please send the file by e-mail to (my github nickname)@outlook.com

**Comment by cubicibo** [comment]
Two questions, to help me debugging: 
1. Did SUPer report `=> Stream has a PTS/DTS issue!!` at the end of the encode process?
2. Was `--ahead` used? (`Allow palette update buffering` in the GUI)

**Comment by Alllen** [comment]
> Two questions, to help me debugging:
> 
> 1. Did SUPer report `=> Stream has a PTS/DTS issue!!` at the end of the encode process?
> 2. Was `--ahead` used? (`Allow palette update buffering` in the GUI)

1. Yes. I didn't notice before.
2. Yes. I used to always turn this option on.
-----------
Sorry for the late reply as I haven't had internet access lately. With SUPer's latest code (20250520), the problem seems to have been solved, and the time of generating the pes file is error free!

**Comment by cubicibo** [comment]
I did not change any of this code so the bug is still in SUPer but it is triggered occasionally... Can you re-generate the file with the faulty version and send in both .SUP and entire debug log report?

**Comment by Alllen** [comment]
> I did not change any of this code so the bug is still in SUPer but it is triggered occasionally... Can you re-generate the file with the faulty version and send in both .SUP and entire debug log report?

Sent.

**Comment by cubicibo** [comment]
Thanks! Can you import this file in Scenarist and try to **Encode → Build** or **Rebuild** the PES? Is there any error or warning at the end of the process? Is it enabling "Acquisition Point Interval", akin to when you import bad .PES files? [testA.zip](https://github.com/user-attachments/files/20412975/testA.zip)

I need to know how SBD reacts to implement a correct fix in SUPer.

**Comment by Alllen** [comment]
> Thanks! Can you import this file in Scenarist and try to **Encode → Build** or **Rebuild** the PES? Is there any error or warning at the end of the process? Is it enabling "Acquisition Point Interval", akin to when you import bad .PES files? [testA.zip](https://github.com/user-attachments/files/20412975/testA.zip)
> 
> I need to know how SBD reacts to implement a correct fix in SUPer.

The error messages and generated files are the same for build and rebuild:
![Image](https://github.com/user-attachments/assets/823596e5-0ce7-4057-96e3-662d2585c2a7)

> Error : [PG=test.pes Epoch=Epoch#1, DisplaySet=DisplaySet#177 StartTime=01:17:47:18] .  *** this DisplaySet will be discarded ***.  The Time from StartTime of previous DisplaySet to StartTime is too close.

---------
[testA_build.zip](https://github.com/user-attachments/files/20435184/testA_build.zip)

**Comment by cubicibo** [comment]
Thank you! SBD encoder is not really good, as expected. I have an idea on how to fix it, hopefully by the end of june.

**Comment by cubicibo** [comment]
Hi again, can you please try the version linked above with the BDN XML that generated the problem?

You can enable all the options you want. There should be not "PTS/DTS issue" message anymore and the timing should be correct in Scenarist.

**Comment by Alllen** [comment]
![Image](https://github.com/user-attachments/assets/367370ab-5c52-49e8-a8ac-aec1e604474a)

```
SUPer ERRO : Incorrect PTS-DTS at 01:17:47:18, DS:S=40:PU=False, stream is out of spec.
 SUPer ERRO : => Stream has a PTS/DTS issue!!
 SUPer ERRO : => Output PGS is not compliant. Expect display issues or decoder crash.
 SUPer ERRO : PES+MUI not generated as the stream is not compliant.
```

With SUPer's latest master (20250615), the problem still seems to exist, the pes file is not generated, the sup is generated and the error is reported at the end of the log as above.

**Comment by cubicibo** [comment]
Please send the BDN XML+PNG by e-mail. I cannot debug the problem without it.

EDIT: you used latest master. You need to add the changes of https://github.com/cubicibo/SUPer/pull/47
To do this, you can either:
- download https://github.com/cubicibo/SUPer/pull/47.patch then `git apply 47.patch`
- simply copy-paste render2.py content from [this version](https://github.com/cubicibo/SUPer/blob/cea0c88b86dca45bbc93ff93c9fa1e4233ec51fc/SUPer/render2.py) to your local file.

Please try again once you have performed one out of the two operation.

**Comment by Alllen** [comment]
> Please send the BDN XML+PNG by e-mail. I cannot debug the problem without it.
> 
> EDIT: you used latest master. You need to add the changes of [cubicibo/SUPer#47](https://github.com/cubicibo/SUPer/pull/47) To do this, you can either:
> 
> * download https://github.com/cubicibo/SUPer/pull/47.patch then `git apply 47.patch`
> * simply copy-paste render2.py content from [this version](https://github.com/cubicibo/SUPer/blob/cea0c88b86dca45bbc93ff93c9fa1e4233ec51fc/SUPer/render2.py) to your local file.
> 
> Please try again once you have performed one out of the two operation.

Sample sent!

**Comment by cubicibo** [comment]
Thank you very much, fixed!
